# Generated by Django 2.1.15 on 2020-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameCompat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField()),
                ('name2', models.TextField()),
                ('jumsu1', models.IntegerField(default=0)),
                ('jumsu2', models.IntegerField(default=0)),
            ],
        ),
    ]
