# Generated by Django 2.1.15 on 2020-10-06 07:33

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, upload_to='facePhotos')),
                ('user_img2', imagekit.models.fields.ProcessedImageField(upload_to='facePhotos')),
            ],
        ),
        migrations.CreateModel(
            name='FaceReadingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_shape', models.TextField()),
                ('eyebrow_interval', models.TextField()),
                ('eye_size', models.TextField()),
                ('eye_interval', models.TextField()),
                ('eye_tail', models.TextField()),
                ('nose_length', models.TextField()),
                ('nose_width', models.TextField()),
                ('mouth_length', models.TextField()),
                ('mouth_thickness', models.TextField()),
                ('mouth_tail', models.TextField()),
                ('eyebrow_result', models.TextField()),
                ('eye_result', models.TextField()),
                ('nose_result', models.TextField()),
                ('mouth_result', models.TextField()),
                ('total', models.TextField()),
                ('total_result', models.TextField()),
                ('user_img', models.ImageField(blank=True, upload_to='facePhotos')),
            ],
        ),
        migrations.CreateModel(
            name='NameCompat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField()),
                ('name2', models.TextField()),
                ('jumsu1', models.IntegerField(default=0)),
                ('jumsu2', models.IntegerField(default=0)),
            ],
        ),
    ]
