# Generated by Django 2.1.15 on 2020-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceReadingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_shape', models.TextField()),
                ('eyebrow_interval', models.TextField()),
                ('eye_size', models.TextField()),
                ('eye_interval', models.TextField()),
                ('eye_tail', models.TextField()),
                ('nose_length', models.TextField()),
                ('nose_width', models.TextField()),
                ('mouth_length', models.TextField()),
                ('mouth_thickness', models.TextField()),
                ('mouth_tail', models.TextField()),
                ('eyebrow_result', models.TextField()),
                ('eye_result', models.TextField()),
                ('nose_result', models.TextField()),
                ('mouth_result', models.TextField()),
                ('total', models.TextField()),
                ('total_result', models.TextField()),
                ('user_img', models.ImageField(blank=True, upload_to='facePhotos')),
            ],
        ),
    ]
